### ISSUE TITLE
Offline env usage

### ISSUE THREAD

**Issue by rwanito** [ansible-community/vscode-ansible#120]
Hi !

I use code-server in offline env.
I've installted this extension to write ansible config files.
But vscode tells me that he cannot hit for example : https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-meta.json

Is exists a solution to bypass this or package this ?

Thanks !

**Comment by ssbarnea** [comment]
Yes, you can override its config by defining your own schema patterns and location of schemas. Read https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml

The patterns defined by this extension can be found at https://github.com/ansible-community/vscode-ansible/blob/master/package.json#L136-L202 and anything setup by you manually will take precedence.

In the future  we may switch to local schemas produced by ansible itself, unique to your setup but for the moment that is only a long term plan, basically because these schemas are not mature yet and we update them often, much more often than we update the extension code.

In fact your offline use-case means you cannot benefit from [json-schema store](https://www.schemastore.org/json/) at all, one major feature of redhat-yaml extension.

**Comment by rwanito** [comment]
Thanks for your reply !

Can the extension work with the command ansible-lint ?
In fact, I can use this command to detect errors, it may be a good feature to use internet when it's possible or ansible-lint when offline ?

**Comment by ssbarnea** [comment]
This extension does also run ansible-lint and reports found errors, the only thing you need to do is to install it yourself. If it is in path it will use it but you can also configure the path. Read https://github.com/ansible-community/vscode-ansible/blob/master/README.md and check the first bullet on known issues.

The easiest way to discover if it works or not is to avoid adding a name for a task. The linter should highlight that issue and report it inside the Problems. You need to open the file to have it linted, current version does not lint entire repository  , not yet.
